In [27]:
import random
import torch
import numpy as np

In [15]:
def shuffle_aligned_list(data):
  """Random shuffle data (x and y)"""
  indices = list(range(len(data[0])))
  random.shuffle(indices) #inplace shuffle indice

  return [d[indices] for d in data]

In [2]:
# define data loader
def data_loader(data, batch_size, shuffle = True):
  """Generate batches of data"""
  if shuffle:
    # do data shuffling
    data = shuffle_aligned_list(data)

  batch_count = 0
  while True:
    if batch_count * batch_size + batch_size > len(data[0]):
      # if it is last batch, then reload data
      batch_count = 0

      if shuffle:
        data = shuffle_aligned_list(data)

    # get start and end indice
    start = batch_count * batch_size
    end = start + batch_size
    batch_count += 1
    
    yield [d[start:end] for d in data]

In [28]:
x = np.array(range(1, 101)).reshape((-1,5))
y = np.array(range(1, 21)).reshape((-1,1))

In [19]:
data_loader((x,y), batch_size)

<generator object data_loader at 0x7fdf16038620>

In [22]:
epochs = 10
batch_size = 5
batch_loader = data_loader((x,y), batch_size)
for i in range(epochs):                    # one eopch run all data once
  batch_x, batch_y = next(batch_loader)
  for j in range(len(x) // batch_size):    
    if int(i %2) == 0:
      print('Epoch %d'%int(i/2))
      print(f'x: {batch_x}, y: {batch_y}')

Epoch 0
x: [[ 71  72  73  74  75]
 [ 61  62  63  64  65]
 [  1   2   3   4   5]
 [ 96  97  98  99 100]
 [ 66  67  68  69  70]], y: [[15]
 [13]
 [ 1]
 [20]
 [14]]
Epoch 0
x: [[ 71  72  73  74  75]
 [ 61  62  63  64  65]
 [  1   2   3   4   5]
 [ 96  97  98  99 100]
 [ 66  67  68  69  70]], y: [[15]
 [13]
 [ 1]
 [20]
 [14]]
Epoch 0
x: [[ 71  72  73  74  75]
 [ 61  62  63  64  65]
 [  1   2   3   4   5]
 [ 96  97  98  99 100]
 [ 66  67  68  69  70]], y: [[15]
 [13]
 [ 1]
 [20]
 [14]]
Epoch 0
x: [[ 71  72  73  74  75]
 [ 61  62  63  64  65]
 [  1   2   3   4   5]
 [ 96  97  98  99 100]
 [ 66  67  68  69  70]], y: [[15]
 [13]
 [ 1]
 [20]
 [14]]
Epoch 1
x: [[16 17 18 19 20]
 [76 77 78 79 80]
 [46 47 48 49 50]
 [31 32 33 34 35]
 [26 27 28 29 30]], y: [[ 4]
 [16]
 [10]
 [ 7]
 [ 6]]
Epoch 1
x: [[16 17 18 19 20]
 [76 77 78 79 80]
 [46 47 48 49 50]
 [31 32 33 34 35]
 [26 27 28 29 30]], y: [[ 4]
 [16]
 [10]
 [ 7]
 [ 6]]
Epoch 1
x: [[16 17 18 19 20]
 [76 77 78 79 80]
 [46 47 48 49 50]
 [31 32 33 34

In [32]:
from torch.utils.data import Dataset, DataLoader
class CustomDataset(Dataset):
  """self defined dataset"""

  def __init__(self, data):
    self.x = data[0]
    self.y = data[1]

  def __len__(self):
    return len(self.x)

  def __getitem__(self, idx):

    x = torch.tensor(self.x[idx])
    y = torch.tensor(self.y[idx])

    return x, y

In [33]:
# construct self-define dataset
custom_dataset = CustomDataset([x, y])
# use index read data
custom_dataset[0]

(tensor([1, 2, 3, 4, 5]), tensor([1]))

In [34]:
# define data loader
custom_dataloader = DataLoader(custom_dataset, batch_size = 5, shuffle = True)

# read one data
next(iter(custom_dataloader))

[tensor([[ 51,  52,  53,  54,  55],
         [ 21,  22,  23,  24,  25],
         [ 61,  62,  63,  64,  65],
         [ 56,  57,  58,  59,  60],
         [ 96,  97,  98,  99, 100]]), tensor([[11],
         [ 5],
         [13],
         [12],
         [20]])]

In [35]:
epochs = 10
for i in range(epochs):
  for data in custom_dataloader:
    if int(i % 2) == 0:
      print('Epoch %d' %int(i/2))
      print(f'x: {data[0]}, y: {data[1]}')

Epoch 0
x: tensor([[36, 37, 38, 39, 40],
        [ 1,  2,  3,  4,  5],
        [61, 62, 63, 64, 65],
        [71, 72, 73, 74, 75],
        [56, 57, 58, 59, 60]]), y: tensor([[ 8],
        [ 1],
        [13],
        [15],
        [12]])
Epoch 0
x: tensor([[11, 12, 13, 14, 15],
        [21, 22, 23, 24, 25],
        [26, 27, 28, 29, 30],
        [31, 32, 33, 34, 35],
        [91, 92, 93, 94, 95]]), y: tensor([[ 3],
        [ 5],
        [ 6],
        [ 7],
        [19]])
Epoch 0
x: tensor([[ 16,  17,  18,  19,  20],
        [ 51,  52,  53,  54,  55],
        [ 96,  97,  98,  99, 100],
        [ 41,  42,  43,  44,  45],
        [ 86,  87,  88,  89,  90]]), y: tensor([[ 4],
        [11],
        [20],
        [ 9],
        [18]])
Epoch 0
x: tensor([[ 6,  7,  8,  9, 10],
        [76, 77, 78, 79, 80],
        [46, 47, 48, 49, 50],
        [81, 82, 83, 84, 85],
        [66, 67, 68, 69, 70]]), y: tensor([[ 2],
        [16],
        [10],
        [17],
        [14]])
Epoch 1
x: tensor([[46, 47,