In [1]:
import torch

In [2]:
x = torch.rand((2,2))
y = torch.rand((2,2))
z = torch.rand((2,2), requires_grad= True)
a = x + y
b = a + z

In [3]:
a

tensor([[0.8600, 0.8193],
        [1.3577, 0.8277]])

In [4]:
b

tensor([[1.3863, 1.0536],
        [1.7717, 1.0167]], grad_fn=<AddBackward0>)

In [5]:
print(f'x: {x.requires_grad}, y: {y.requires_grad}, z: {z.requires_grad}')
print(f'a: {a.requires_grad}, y: {b.requires_grad}')

x: False, y: False, z: True
a: False, y: True


In [6]:
print(f'x: {x.grad_fn}, y:{y.grad_fn}, z:{z.grad_fn}')
print(f'a: {a.grad_fn}, b:{b.grad_fn}')

x: None, y:None, z:None
a: None, b:<AddBackward0 object at 0x7f634e845860>


In [7]:
x = torch.ones((2,2), requires_grad=True)
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [8]:
y = x +2
y, y.requires_grad

(tensor([[3., 3.],
         [3., 3.]], grad_fn=<AddBackward0>), True)

In [9]:
z = y*y*3
out = z.mean()
print(z)
print(out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>)
tensor(27., grad_fn=<MeanBackward0>)


In [11]:
print(x.grad_fn)
print(y.grad_fn)
print(z.grad_fn)
print(out.grad_fn)

None


In [12]:
out.backward()

In [13]:
x.grad

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])

In [15]:
a = torch.randn(2, 2, requires_grad= False)
a = ((a * 3) / (a -1 ))
b = (a * a).sum()
print(b.requires_grad, a.requires_grad)
print(b.grad_fn)

False False
None


In [16]:
# use torch.no_grad()
a = torch.randn(2, 2)
a = ((a * 3) / (a - 1))
with torch.no_grad():
  b = (a * a).sum()
print(b.requires_grad, b.grad_fn)

False None
