### 作業目的: 更加熟習pytorch的tensor操作

pytorch中有提供很多的API，讓使用者針對tensor進行各式各樣的操作，本次的作業希望讀者由pytorch的[官方網站](https://pytorch.org/docs/stable/torch.html)中選定四個針對tensor操作的API，對他的使用方法進行範例操作演練。

### 選定的API 函數

* torch.from_array() / tensor.numpy()
* torch.unsqueeze() / torch.squeeze()
* tensor.transpose() / tensor.permute()
* torch.reshape() / tensor.view()
* torch.randn() / torch.rand() / torch.randint()

In [1]:
# Import torch and other required modules
import torch
import numpy as np

### Function 1 - torch.from_array() / tensor.numpy()

In [2]:
# Example 1 - change torch.tensor to numpy array and change numpy array to torch tensor
a = np.random.rand(1,2,3,3)
print(f'a: {type(a)}, {a.dtype}')
b = torch.from_numpy(a)
print(f'b: {type(b)}, {b.dtype}')
c = torch.tensor(a)
print(f'c: {type(c)}, {c.dtype}')
d = c.numpy()
print(f'd: {type(d)}, {d.dtype}')

a: <class 'numpy.ndarray'>, float64
b: <class 'torch.Tensor'>, torch.float64
c: <class 'torch.Tensor'>, torch.float64
d: <class 'numpy.ndarray'>, float64


In [3]:
# Example 2 - we can see that the transformed dtype will in accordance with the original one
a = np.random.randint(low=0, high=10, size=(2,2))
print(f'a: {type(a)}, {a.dtype}')
b = torch.from_numpy(a)
print(f'b: {type(b)}, {b.dtype}')
c = torch.tensor(a)
print(f'c: {type(c)}, {c.dtype}')
d = c.numpy()
print(f'd: {type(d)}, {d.dtype}')

a: <class 'numpy.ndarray'>, int64
b: <class 'torch.Tensor'>, torch.int64
c: <class 'torch.Tensor'>, torch.int64
d: <class 'numpy.ndarray'>, int64


### Function 2 - torch.unsqueeze() / torch.squeeze()

In [4]:
# Example 1 - expanding/squeeze the dimension
a = torch.tensor([[[1,2],[2,3]]], dtype=torch.float32)
print(f'Before unsqueeze/squeeze: {a.size()}')

b = torch.unsqueeze(a, dim=0)
print(f'After unsqueeze: {b.size()}')

c = torch.squeeze(a, dim=0)
print(f'After squeeze: {c.size()}')

Before unsqueeze/squeeze: torch.Size([1, 2, 2])
After unsqueeze: torch.Size([1, 1, 2, 2])
After squeeze: torch.Size([2, 2])


In [5]:
# Example 2 - expanding/squeeze the dimension
a = torch.tensor([[1,2],[2,3]], dtype=torch.float32)
print(f'Before unsqueeze/squeeze: {a.size()}')

b = torch.unsqueeze(a, dim=1)
print(f'After unsqueeze: {b.size()}')

c = torch.squeeze(a, dim=1)
print(f'After squeeze: {c.size()}')

Before unsqueeze/squeeze: torch.Size([2, 2])
After unsqueeze: torch.Size([2, 1, 2])
After squeeze: torch.Size([2, 2])


### Function 3 - tensor.transpose() / tensor.permute()

In [6]:
# Example 1 - transpose and permute the tensor dimension
a = torch.tensor([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]])
print(f'Original shape: {a.size()}')

b = a.transpose(dim0=0, dim1=2)
print(f'Transpose shape: {b.size()}')

c = a.permute((1,2,0))
print(f'Permute shape: {c.size()}')

Original shape: torch.Size([2, 2, 3])
Transpose shape: torch.Size([3, 2, 2])
Permute shape: torch.Size([2, 3, 2])


In [7]:
# Example 2 - sharing memory
a = torch.tensor([[1,2],[3,4]])
print(f'Original shape: {a.size()}')
print(a)

b = a.transpose(dim0=0, dim1=1)
print(f'Transpose shape: {b.size()}')
print(b)

c = a.permute((0,1))
print(f'Permute shape: {c.size()}')
print(c)

print('\n')
# change a[0][0] to 0
a[0][0] = 0

# check the value of a, b, c
print(f'a: {a}')
print(f'b: {b}')
print(f'c: {c}')

Original shape: torch.Size([2, 2])
tensor([[1, 2],
        [3, 4]])
Transpose shape: torch.Size([2, 2])
tensor([[1, 3],
        [2, 4]])
Permute shape: torch.Size([2, 2])
tensor([[1, 2],
        [3, 4]])


a: tensor([[0, 2],
        [3, 4]])
b: tensor([[0, 3],
        [2, 4]])
c: tensor([[0, 2],
        [3, 4]])


In [8]:
print(a.data_ptr()) 
print(b.data_ptr())
print(c.data_ptr())

140316317518208
140316317518208
140316317518208


### Function 4 - torch.reshape() / tensor.view()

In [9]:
# Example 1 - reshape and view to change tensor's dimension

a = torch.tensor([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]])
print(f'Original shape: {a.size()}')

b = torch.reshape(a, shape=(-1, 3))
print(f'Reshape shape: {b.size()}')

c = a.view((-1,3))
print(f'View shape: {c.size()}')

Original shape: torch.Size([2, 2, 3])
Reshape shape: torch.Size([4, 3])
View shape: torch.Size([4, 3])


In [10]:
# Example 2 - sharing memory and continuous data
a = torch.tensor([[1,2],[3,4]])
print(f'Original shape: {a.size()}')
print(a)

b = torch.reshape(a, (-1,))
print(f'Transpose shape: {b.size()}')
print(b)

c = a.view((-1))
print(f'Permute shape: {c.size()}')
print(c)

print('\n')
# change a[0][0] to 0
a[0][0] = 0

# check the value of a, b, c
print(f'a: {a}')
print(f'b: {b}')
print(f'c: {c}')

Original shape: torch.Size([2, 2])
tensor([[1, 2],
        [3, 4]])
Transpose shape: torch.Size([4])
tensor([1, 2, 3, 4])
Permute shape: torch.Size([4])
tensor([1, 2, 3, 4])


a: tensor([[0, 2],
        [3, 4]])
b: tensor([0, 2, 3, 4])
c: tensor([0, 2, 3, 4])
