### 作業目的: 更加熟習pytorch的tensor操作

pytorch中有提供很多的API，讓使用者針對tensor進行各式各樣的操作，本次的作業希望讀者由pytorch的[官方網站](https://pytorch.org/docs/stable/torch.html)中選定四個針對tensor操作的API，對他的使用方法進行範例操作演練。

### 選定的API 函數

**請寫下選定的API functions**

ex:
* torch.from_array() / tensor.numpy()
* torch.unsqueeze() / torch.squeeze()
* tensor.transpose() / tensor.permute()
* torch.reshape() / tensor.view()

In [1]:
# Import torch and other required modules
import torch
import numpy as np

### 範例:
### Function 1 - torch.from_array() / tensor.numpy()

In [2]:
# Example 1 - 將torch tensor與numpy ndarray互相轉換
a = np.random.rand(1,2,3,3)
print(f'a: {type(a)}, {a.dtype}')
b = torch.from_numpy(a)
print(f'b: {type(b)}, {b.dtype}')
c = torch.tensor(a)
print(f'c: {type(c)}, {c.dtype}')
d = c.numpy()
print(f'd: {type(d)}, {d.dtype}')

a: <class 'numpy.ndarray'>, float64
b: <class 'torch.Tensor'>, torch.float64
c: <class 'torch.Tensor'>, torch.float64
d: <class 'numpy.ndarray'>, float64


In [13]:
# Example 2 - 經過轉換後，torch tensor與numpy array依然有相近的資料型態
a = np.random.randint(low=0, high=10, size=(2,2))
print(f'a: {type(a)}, {a.dtype}')
b = torch.from_numpy(a)
print(f'b: {type(b)}, {b.dtype}')
c = torch.tensor(a)
print(f'c: {type(c)}, {c.dtype}')
d = c.numpy()
print(f'd: {type(d)}, {d.dtype}')

a: <class 'numpy.ndarray'>, int64
b: <class 'torch.Tensor'>, torch.int64
c: <class 'torch.Tensor'>, torch.int64
d: <class 'numpy.ndarray'>, int64


### Function 1 - *torch.unsqueeze() / torch.squeeze()*

In [15]:
# Example 1 - ### Unsqueeze Returns a new tensor with a dimension of size one inserted at the specified position.
x = torch.tensor([1, 2, 3, 4])
print(torch.unsqueeze(x, 0))
print(torch.unsqueeze(x, 1))

tensor([[1, 2, 3, 4]])
tensor([[1],
        [2],
        [3],
        [4]])


In [17]:
# Example 2 - Returns a tensor with all the dimensions of input of size 1 removed.
x = torch.zeros(2,1,2,1,2)
print(x.size())
y = torch.squeeze(x)
print(y.size())
# When dim is given, a squeeze operation is done only in the given dimension
y = torch.squeeze(x, 0)
print(y.size())
y = torch.squeeze(x,1)
print(y.size())

torch.Size([2, 1, 2, 1, 2])
torch.Size([2, 2, 2])
torch.Size([2, 1, 2, 1, 2])
torch.Size([2, 2, 1, 2])


### Function 2 - tensor.transpose() / tensor.permute()

In [18]:
# Example 1 - transpose: Returns a tensor that is a transposed version of input. The given dimensions dim0 and dim1 are swapped.
### your code ###
x = torch.randn(2, 3)
print("x",x)
print("transpose(x,0,1)",torch.transpose(x, 0, 1))

x tensor([[-0.2913,  0.4091,  0.3064],
        [-1.6714,  1.2433,  2.0563]])
transpose(x,0,1) tensor([[-0.2913, -1.6714],
        [ 0.4091,  1.2433],
        [ 0.3064,  2.0563]])


In [24]:
# Example 2 - ### your explanation ###
### your code ###
y = x.permute((1,0))
y

tensor([[-0.2913, -1.6714],
        [ 0.4091,  1.2433],
        [ 0.3064,  2.0563]])

### Function 3 - torch.reshape() / tensor.view()

In [26]:
# Example 1 - Reshape
"""
  Returns a tensor with the same data and number of elements as input,
but with the specified shape. When possible, the returned tensor will be a view of input. 
Otherwise, it will be a copy. Contiguous inputs and inputs with compatible strides can be reshaped without copying,
but you should not depend on the copying vs. viewing behavior.
"""
### your code ###
a = torch.arange(4.)
print(torch.reshape(a, (2,2)))
b = torch.tensor([[0,1], [2,3]])
print(torch.reshape(b, (-1,)))


tensor([[0., 1.],
        [2., 3.]])
tensor([0, 1, 2, 3])


In [32]:
# Example 2 - ### tensor.view() -> New view of array with the same data.
### your code ###

x = np.array([(1, 2),(3,4)], dtype=[('a', np.int8), ('b', np.int8)])
xv = x.view(dtype=np.int8).reshape(-1,2)
xv

array([[1, 2],
       [3, 4]], dtype=int8)

### Function 4 - torch.split()/ tensor.split()

In [33]:
# Example 1 - ### Splits the tensor into chunks. Each chunk is a view of the original tensor.
### your code ###
a = torch.arange(10).reshape(5, 2)
print(a)
print(torch.split(a, 2))
print(torch.split(a, [1,4]))

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])
(tensor([[0, 1],
        [2, 3]]), tensor([[4, 5],
        [6, 7]]), tensor([[8, 9]]))
(tensor([[0, 1]]), tensor([[2, 3],
        [4, 5],
        [6, 7],
        [8, 9]]))


In [34]:
# Example 2 - tensor.split() Split an array into multiple sub-arrays as views into ary.
x = np.arange(9.)
print(np.split(x, 3))
x = np.arange(8.)
np.split(x, [3, 5, 6, 10])

[array([0., 1., 2.]), array([3., 4., 5.]), array([6., 7., 8.])]


[array([0., 1., 2.]),
 array([3., 4.]),
 array([5.]),
 array([6., 7.]),
 array([], dtype=float64)]

In [ ]:
# size or sections